### ISSUE TITLE
Copy fails with "No handler found for uri..."

### ISSUE THREAD

**Issue by bemeyert** [mallocator/Elasticsearch-Exporter#110]
Hi all,

I want to copy and index from on node to another and it fails. Here the output:
```
[root@salttestvm70 Elasticsearch-Exporter]# time node exporter.js -th localhost -si logstash-2015.10.24 -sh other-host
Elasticsearch Exporter - Version 2.0.0
Caught exception in Main process: Error: There was an error trying to parse a json response from the server. Server response:
No handler found for uri [/logstash-2015.10.24/_mapping/image/x-icon] and method [PUT]
Error: There was an error trying to parse a json response from the server. Server response:
No handler found for uri [/logstash-2015.10.24/_mapping/image/x-icon] and method [PUT]
    at Object.request.buffer_concat (/root/Elasticsearch-Exporter/drivers/elasticsearch.driver.js:192:19)
    at IncomingMessage.<anonymous> (/root/Elasticsearch-Exporter/drivers/elasticsearch.driver.js:229:38)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
Exit code 2: Uncaught Exception
Fetched Entries:        0 documents
Processed Entries:      0 documents
Source DB Size:         0 documents
```

Someone seems to stumble over a mapping containing a "/". BTW The used version is  1.1.2

**Comment by bemeyert** [comment]
The above mentioned version applies to Elasticsearch ;)

**Comment by mallocator** [comment]
Thanks for reporting the bug. I couldn't find anything in the Es docs regarding slashes in types. I assume urlencoding the type section will fix the issue. Have you had any experience with this?

**Comment by bemeyert** [comment]
@mallocator Cheers, I will give this a try.

**Comment by bemeyert** [comment]
This issue seems to be fixed. The same command as above ran without the metioned error. Thanks a lot! But I stumbled over two other issues: #112 & #113

**Comment by mallocator** [comment]
Thanks for filing them. I'll take a stab at fixing them as soon as I have time.
